// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cycade/go-samples/internal/biz"
	"github.com/cycade/go-samples/internal/data"
	"github.com/cycade/go-samples/internal/service"
)

// Injectors from wire.go:

func initApp() service.DeploymentService {
	deploymentRepo := data.NewDeploymentRepo()
	deploymentUsecase := biz.NewDeploymentUsecase(deploymentRepo)
	deploymentService := service.NewDeploymentService(deploymentUsecase)
	return deploymentService
}
